import Guide from "../components/Guide"
import CodeBox from "../components/CodeBox"
import Palette from "../components/Palette"

export default function Artist() {

    let lecture = `
        Our app is made of components, which are reusable building blocks of a site. <b>React Components</b> is an exported Javascript function or class, which may be housed in its own <code><b>.js</b>, <b>.ts</b>, <b>.jsx</b> or <b>.tsx</b> file</code>.

        <br><br>
        You can write code for your own components, or import pre-made ones from <a href="https://madewithreactjs.com/ui-library"><u>open-source UI libraries</u></a>.

        <br><br>
        In FreeTheEgg, the thick bar on the top of our site is called a <b><code>&lt;Header&gt;</code></b>. 
        That thin, black bar fixed below our page is called a <b><code>&lt;Footer&gt;</code></b>. 
        The box where this text is right now is a <b><code>&lt;Guide&gt;</code></b>.

        <br><br>
        <b>Props</b> are values that can be passed into the component's tag which can be a string, number, boolean, array, object or class.
        You can change how our website looks by clicking the boxes inside <b><code>&lt;Palette&gt;</code></b>. The boxes generated by Palette are from <b>an array of color strings</b> passed as a prop. 
        Header is painted by <b>a string</b> passed to backgroundClass.
        You can preview the code that Header is consuming behind-the-scenes in real-time through <b><code>&lt;CodeBox&gt;</code></b>!`

    return (
        <div id="artistWorkspace" className="appPage">
            <Guide instructions = "<b>Change the header pattern and background color of this app.</b>">
                {lecture}
            </Guide>
            <div id="paletteView">
                <div id="palettes" style={{ display: "flex" }}>
                    <Palette title="Header" patterns={["pinkcrystal","slateleaves","goldswirls","flowers"]} />
                    <Palette title="Body" colors={["thistle","moccasin","lightgrey","lightcoral","cadetblue","mistyrose"]} />
                </div>
                <CodeBox />
            </div>
        </div>
    )
}