<script>
    import Guide from "../components/Guide.svelte"
    import CodeBox from "../components/CodeBox.svelte"
    import Palette from "../components/Palette.svelte"
</script>

<div id="artistWorkspace" class="appPage">
    <Guide instructions = "<b>Change the header pattern and background color of this app.</b>">
        Our app is made of components, which are reusable building blocks of a site. <b>Svelte Components</b> are HTML, CSS, and JS packed together under one <code><b>.svelte</b></code> file.

        <br><br>
        You can write code for your own components, or import pre-made ones from <a href="https://madewithsvelte.com/ui-library"><u>open-source UI libraries</u></a>.
        
        <br><br>
        In FreeTheEgg, the thick bar on the top of our site is called a <b><code>&lt;Header&gt;</code></b>. 
        That thin, black bar fixed below our page is called a <b><code>&lt;Footer&gt;</code></b>. 
        The box where this text is right now is a <b><code>&lt;Guide&gt;</code></b>.

        <br><br>
        <b>Props</b> are values that can be passed into the component's tag which can be a string, number, boolean, array, object or class.
        You can change how our website looks by clicking the boxes inside <b><code>&lt;Palette&gt;</code></b>. The boxes generated by Palette are from <b>an array of color strings</b> passed as a prop. 
        Header is painted by <b>a string</b> passed to backgroundClass.
        You can preview the code that Header is consuming behind-the-scenes in real-time through <b><code>&lt;CodeBox&gt;</code></b>!
    </Guide>
    <div id="paletteView">
        <div id="palettes">
            <Palette title="Header" patterns={["pinkcrystal","slateleaves","goldswirls","flowers"]} />
            <Palette title="Body" colors={["thistle","moccasin","lightgrey","lightcoral","cadetblue","mistyrose"]} />
        </div>
        <CodeBox />
    </div>
</div>